// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkOd4-uKC2ydk93cDYiKBHydmrbZtvdos',
    appId: '1:512119346213:web:2c9b2db432671e82409bcc',
    messagingSenderId: '512119346213',
    projectId: 'cartadigital-139ba',
    authDomain: 'cartadigital-139ba.firebaseapp.com',
    storageBucket: 'cartadigital-139ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3L92jx3CbvUr7HVbgRzxdNDdEokZFg0',
    appId: '1:512119346213:android:e24063cd41c7d22b409bcc',
    messagingSenderId: '512119346213',
    projectId: 'cartadigital-139ba',
    storageBucket: 'cartadigital-139ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd0RO6v-lTqYVuD0UOnjZHOz-yEcL7MDc',
    appId: '1:512119346213:ios:24081538ebd94bf7409bcc',
    messagingSenderId: '512119346213',
    projectId: 'cartadigital-139ba',
    storageBucket: 'cartadigital-139ba.firebasestorage.app',
    iosBundleId: 'com.example.cartaDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkOd4-uKC2ydk93cDYiKBHydmrbZtvdos',
    appId: '1:512119346213:web:bcfea0def5ae3d85409bcc',
    messagingSenderId: '512119346213',
    projectId: 'cartadigital-139ba',
    authDomain: 'cartadigital-139ba.firebaseapp.com',
    storageBucket: 'cartadigital-139ba.firebasestorage.app',
  );

}