name: pipelineccicd

on:
  push:
    branches:
      - merginincioconfunciones
      - develop
      - main
      - mergeBeta

  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Levantar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Cache de dependencias
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Instalar dependencias
        run: flutter pub get
        working-directory: src/carta_digital

      - name: Correr pruebas
        run: flutter test
        working-directory: src/carta_digital

      - name: Decodificar keystore
        run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > src/carta_digital/android/app/release-key.jks

      - name: Exportar variables de firma
        run: |
          echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Crear APK
        run: flutter build apk --release
        working-directory: src/carta_digital

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: src/carta_digital/build/app/outputs/flutter-apk/app-release.apk
